[32m2024-05-03 17:20:16 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a21af920-401c-4f1c-86db-7cbdb2a58c32 - 20447 - LOGS_CAPTURED - Started capturing logs in process (pid: 20447).
[32m2024-05-03 17:20:16 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a21af920-401c-4f1c-86db-7cbdb2a58c32 - 20447 - topstories - STEP_START - Started execution of step "topstories".
[32m2024-05-03 17:20:33 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - a21af920-401c-4f1c-86db-7cbdb2a58c32 - 20447 - topstories - STEP_FAILURE - Execution of step "topstories" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "topstories"::

TypeError: MetadataValue() takes no arguments

Stack Trace:
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/usr/local/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 465, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dagster/tutorial/tutorial/assets.py", line 43, in topstories
    "preview": MetadataValue(df.head().to_markdown(), "Preview of the data"),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0m
